site_name: NB-Classifier
site_author: Yogeshvar 
nav: 
  - Home: index.md
theme: readthedocs

extra_css:
    - css/extra.css

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_math
